sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ymy19990505..
  alioss:
    access-key-id: LTAI5tMQEEei5fhx3Y2HDZrZ
    access-key-secret: ODkPz7s4ZPYrELKxK869fyosygESlv
    bucket-name: ymy-take-out
    endpoint: oss-cn-wulanchabu.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: ymy19990505..
    database: 6
  wechat:
    appid: wx3acbb88a2b9f6e4f
    secret: 18a9bad8ca649c19056ed7f88e451fa2
    # 微信支付相关
#    mchid: 1561414331
#    mch-serial-no: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
